copy e:\pc\*.pc c:\copias\pc /y
copy g:\pc\*.pc c:\copias\rutinas /y
copy g:\pc\*.c c:\copias\rutinas /y
copy e:\pc\a.bat c:\copias\pc /y
copy e:\pc\pro22.mak c:\copias\pc /y
copy g:\nomina\*.* c:\copias\nomina /y
xcopy g:\querys\*.* c:\copias\querys /s /u
xcopy g:\contabilidad\*.* c:\copias\contabilidad /s /u
xcopy g:\produccion\*.* c:\copias\produccion /s /u
copy g:\lib\*.* c:\copias\lib /y
copy g:\libs\*.* c:\copias\libs /y
copy g:\reportes\*.* c:\copias\reportes /y
